### ISSUE TITLE
Linux alsa + multithread compile fails on recent alsa, alsa/iatomic.h unavailable

### ISSUE THREAD

**Issue by mberkowski** [RTcmix/RTcmix#22]
Hi there - 

Compiling on Linux (Ubuntu 19.10) `--with-alsa --with-multithread` fails with recent alsa (1.1.9) as `alsa/iatomic.h` is no longer included in alsa.

It appears to have been removed in alsa 1.1.2 based on https://www.alsa-project.org/wiki/Changes_v1.1.1_v1.1.2

```
In file included from /RTcmix/include/ugens.h:12,
                 from Ooscili.cpp:6:
//RTcmix/include/rt_types.h:71:10: fatal error: alsa/iatomic.h: No such file or directory
   71 | #include <alsa/iatomic.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:153: Ooscili.o] Error 1
```

**Comment by johgibso** [comment]
Thanks, Michael. None of us use Linux any more really, so we are flying blind these days.

In a more verbose change log for that alsa version bump, it says:

- pcm: Remove home brew atomic operations
We've had a few home brew atomic operations in a couple of places in
the PCM code. This was for supporting the concurrent accesses, but in
practice, it couldn't cover the race properly by itself alone.
Since we have a wider concurrency protection via mutex now, we can get
rid of these atomic codes, which worsens the portability
significantly.

So, do we try to use the atomic operations available in the Linux kernel, which appear to have the same semantics, or do we just compile without atomic support, assuming that the driver handles it correctly with mutexes?

John Gibson

**Comment by dougscott** [comment]
We should figure out how to get the compiler to detect the version
difference which no longer supports atomics.  Then at least older versions
will have it.  Newer ones should take the same compile route as "not
Linux/ALSA and not Mac".

-Doug

**Comment by dougscott** [comment]
Anyone who wants to try to tackle this issue, here's a starting point:  https://stackoverflow.com/questions/2287451/how-to-perform-atomic-operations-on-linux-that-work-on-x86-arm-gcc-and-icc

**Comment by dougscott** [comment]
Update:  I am using much newer stdlib libraries to get multi-thread support working on Linux.

**Comment by dougscott** [comment]
Fix for this has now been checked in.  Latest version(s) allow multithreaded support for Linux.
